sticky-piston-push-strength: 3
sticky-piston-pull-strength: 3
piston-push-strength: 3
piston-pull-strength: 3
all-pistons-are-sticky: false
log-debug: false
sticky-blocks:
  - HONEY_BLOCK
  - SLIME_BLOCK
unmoveable-blocks:
  - PISTON_HEAD
  - MOVING_PISTON
  - STICKY_PISTON
  - PISTON
  - AIR
  - BEDROCK
  - OBSIDIAN
  - FURNACE
  - BARRIER
  - BEACON
  - COMMAND_BLOCK
  - CONDUIT
  - CRYING_OBSIDIAN
  - ENCHANTING_TABLE
  - END_GATEWAY
  - END_PORTAL
  - END_PORTAL_FRAME
  - ENDER_CHEST
  - GRINDSTONE
  - JUKEBOX
  - LIGHT
  - LODESTONE
  - SPAWNER
  - NETHER_PORTAL
  - REINFORCED_DEEPSLATE
  - RESPAWN_ANCHOR
  - SCULK_CATALYST
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID