name: piston-tweaks
version: '${version}'

main: dank.net.pistonTweaks.PistonTweaks
bootstrapper: dank.net.pistonTweaks.PistonTweaksBootstrap
loader: dank.net.pistonTweaks.PistonTweaksLoader
api-version: '26.1.2'
load: POSTWORLD
